local theme = {}
theme.neon = {
  bg0      = "#0a0b10",
  bg1      = "#0f111a",
  bg2      = "#131625",
  fg0      = "#e7eaff",
  fg1      = "#cfd3ff",
  muted    = "#8b93c7",
  pink     = "#ff2fb9",
  pink2    = "#ff64d5",
  purple   = "#b468ff",
  blue     = "#4aa3ff",
  cyan     = "#23d7ff",
  teal     = "#14f7c1",
  orange   = "#ff9f43",
  red      = "#ff3860",
  green    = "#31ff9a",
  border0  = "#241a33",
  border1  = "#3a1a52",
}
theme.font          = "JetBrainsMono Nerd Font 10"
theme.font_bold     = "JetBrainsMono Nerd Font Bold 10"
theme.iconfont      = "Symbols Nerd Font 16"
theme.iconfont_big  = "Symbols Nerd Font 18"
theme.bg_normal     = theme.neon.bg0
theme.bg_focus      = theme.neon.bg1
theme.bg_urgent     = theme.neon.red
theme.bg_minimize   = theme.neon.bg2
theme.fg_normal     = theme.neon.fg1
theme.fg_focus      = theme.neon.fg0
theme.fg_urgent     = theme.neon.bg0
theme.fg_minimize   = theme.neon.muted
theme.border_width  = 2
theme.border_normal = theme.neon.border0
theme.border_focus  = theme.neon.pink
theme.border_marked = theme.neon.cyan
theme.useless_gap   = 8
theme.gap_single_client = true
theme.corner_radius = 10
theme.wibar_height  = 38
theme.dock_width    = 62
theme.tag_active_bg = theme.neon.pink
theme.tag_active_fg = theme.neon.bg0
theme.tag_idle_fg   = theme.neon.muted
theme.tag_empty_fg  = theme.neon.border1
theme.clock_fg      = theme.neon.cyan
theme.widget_fg     = theme.neon.fg1
theme.widget_dim_fg = theme.neon.muted
theme.widget_accent = theme.neon.pink
theme.widget_ok     = theme.neon.teal
theme.widget_warn   = theme.neon.orange
theme.dock_icon_fg  = theme.neon.fg0
theme.dock_icon_bg  = theme.neon.bg1
theme.dock_icon_hi  = theme.neon.pink
return theme
